<?php
namespace Database\Seeders;
use App\Models\{FoundationSkNumberSetting,FoundationSkTemplate,Permission};
use Illuminate\Database\Seeder;
class FoundationSkSeeder extends Seeder {
 public function run():void { Permission::findOrCreate('sk-yayasan.view','web'); Permission::findOrCreate('sk-yayasan.manage','web'); $html=<<<'HTML'
<div class="sk-document">
<header class="sk-header"><div class="kop-grid"><div class="kop-logo"><img src="/images/logo-kop-surat-lp.png" alt="Logo NU"></div><div class="kop-text"><div class="kop-small">PENGURUS CABANG NAHDLATUL ULAMA GUNUNGKIDUL</div><div class="kop-name">LEMBAGA PENDIDIKAN MA’ARIF NU</div><div>Jl. Tentara Pelajar, Trimulyo I, Kepek, Wonosari, Gunungkidul-55813</div><div>085122016369&nbsp;&nbsp;◉</div><div class="kop-email">maarifgunungkidul@gmail.com&nbsp;&nbsp;◉</div></div></div><div class="sk-title">SURAT KEPUTUSAN KETUA LP MA’ARIF NU GUNUNGKIDUL</div><div>Nomor : {{nomor_sk}}</div><div>Ketua Lembaga Pendidikan Ma’arif NU Kabupaten Gunungkidul</div></header>
<section><p><strong>Menimbang:</strong></p><ol><li>Bahwa demi meningkatkan kualitas pelayanan pendidikan di {{nama_sekolah}}, maka dipandang perlu mengangkat Guru Tetap yang memenuhi syarat kualifikasi;</li><li>Bahwa Guru tersebut memenuhi syarat untuk diangkat kembali sebagai Guru Tetap di LP. Ma’arif NU PCNU Gunungkidul untuk {{nama_sekolah}}, sesuai dengan kualifikasi tersebut;</li></ol></section>
<section><p><strong>Mengingat:</strong></p><ol><li>Undang-Undang Nomor 20 Tahun 2003 Tentang Sisdiknas;</li><li>Peraturan Pemerintah No. 19 Tahun 2005 tentang Standar Nasional Pendidikan;</li><li>Peraturan Perkumpulan NU Nomor 15 Tahun 2025 Tentang Sistem Pendidikan Nahdlatul Ulama;</li><li>Surat Keputusan LP. Ma’arif NU PBNU Nomor 147/PB.16/A.II.01.21/21/07/2025 Tahun 2025 tentang Pedoman Tata Kelola LP. Ma’arif NU;</li></ol></section>
<section><p><strong>Memperhatikan:</strong> Bahwa tenaga pendidik berikut berstatus aktif di {{nama_sekolah}} sesuai dengan verifikasi data di Aplikasi SiDIKMa-GK pada tahun ditetapkannya keputusan ini.</p></section>
<div class="sk-center"><strong>MEMUTUSKAN</strong></div><p><strong>Menetapkan:</strong></p>
<p><strong>Pertama:</strong> Guru tersebut di bawah ini:</p><table><tr><td>Nama</td><td>: {{nama_lengkap}}</td></tr><tr><td>Tempat, tanggal lahir</td><td>: -</td></tr><tr><td>NUPTK/NPK</td><td>: {{nuptk}}</td></tr><tr><td>EWANUGK</td><td>: {{nis}}</td></tr><tr><td>TMT Pertama</td><td>: -</td></tr><tr><td>Pendidikan, tahun lulus</td><td>: -</td></tr><tr><td>Program Studi</td><td>: -</td></tr><tr><td>Status Kepegawaian</td><td>: -</td></tr></table>
<p>diangkat kembali sebagai Guru Tetap LP. Ma’arif NU PCNU Gunungkidul untuk {{nama_sekolah}} tahun pelajaran {{periode}}, dengan ketugasan yang berlaku, dan kepadanya diberikan gaji pokok serta tunjangan lain yang berlaku di {{nama_sekolah}}.</p>
<p><strong>Kedua:</strong> Keputusan ini berlaku terhitung mulai tanggal - sampai dengan - yang apabila di kemudian hari terdapat kekeliruan di dalamnya, akan diadakan perbaikan dan perhitungan kembali sebagaimana mestinya.</p><p><strong>Ketiga:</strong> Asli Surat Keputusan ini diberikan kepada yang bersangkutan.</p>
<div class="signature">Ditetapkan di : Gunungkidul<br>Pada Tanggal : {{tahun}}<br><br>Pengurus LP Ma’arif NU Kab. Gunungkidul<br>Ketua,<br><br><img class="stamp" src="/images/stempel-lp-maarif.png" alt="Stempel LP Ma'arif"><br><strong>Drs. H. SANGKIN, M.Pd.</strong></div>
<p><strong>Tembusan Yth;</strong></p><ol><li>Kepala Kab. Gunungkidul</li><li>Ketua PCNU Gunungkidul</li><li>Kepala {{nama_sekolah}}</li></ol></div>
HTML;
 $css='.sk-document{font-family:Arial,sans-serif;font-size:12px;line-height:1.45;color:#111827}.sk-header{text-align:center;border-bottom:3px solid #15803d;padding-bottom:12px;margin-bottom:18px}.kop-grid{display:grid;grid-template-columns:125px 1fr;align-items:center;text-align:center;min-height:105px}.kop-logo img{width:108px;height:92px;object-fit:contain}.kop-text{color:#15803d;font-size:11px;line-height:1.35}.kop-small{font-family:Georgia,serif;font-size:16px;letter-spacing:.4px}.kop-name{font-size:23px;font-weight:700}.kop-email{color:#2563a8;text-decoration:underline}.sk-title{font-size:16px;font-weight:700;margin:10px 0 6px}.sk-document section{margin:10px 0}.sk-document ol{margin-top:4px;padding-left:28px}.sk-center{text-align:center;margin:20px 0 12px}.sk-document table{width:100%;border-collapse:collapse;margin:8px 0}.sk-document td{padding:2px 4px;vertical-align:top}.sk-document td:first-child{width:30%}.signature{margin:22px 0 22px 58%;white-space:nowrap}.stamp{width:105px;height:105px;object-fit:contain;display:block;margin:2px 0 -8px 8px}'; FoundationSkTemplate::updateOrCreate(['slug'=>'sk-guru-pegawai'],['name'=>'SK Guru/Pegawai','document_title'=>'Surat Keputusan Yayasan','paper_size'=>'A4','orientation'=>'portrait','html_template'=>$html,'content'=>$html,'css_template'=>$css,'custom_css'=>$css,'is_active'=>true]); FoundationSkNumberSetting::updateOrCreate(['periode'=>'2026/2027'],['nomor_pattern'=>'SK/{{nomor_urut}}/{{tahun}}','nomor_awal'=>1,'nomor_berikutnya'=>1,'digit_nomor'=>4,'nomor_text'=>'SK Yayasan','is_active'=>true]); }
}
