<div class="ma-page" x-data="attendanceGps({ maxAccuracy: {{ $setting?->maximum_accuracy_meters ?? 100 }} })">
<p role="status" aria-live="polite" x-show="gpsMessage" x-text="gpsMessage" style="padding:12px;font-size:13px;color:#52657a"></p>
<button type="button" x-cloak x-show="locating" x-on:click="cancel()" style="margin:0 12px 12px;color:#175cd3;font-weight:600">Batalkan pencarian GPS</button>
<style>
.ma-page{display:grid;gap:1.25rem;color:#52657a}.ma-hero,.ma-card{border:1px solid #dfe8f1;border-radius:1rem;background:#fff;box-shadow:0 10px 30px rgba(22,48,78,.07)}.ma-hero{padding:1.5rem;background:linear-gradient(135deg,#0f6a50,#147ca0);color:#fff}.ma-head,.ma-actions,.ma-status{display:flex;align-items:center;justify-content:space-between;gap:1rem}.ma-title{font-size:1.6rem;font-weight:800}.ma-sub{color:#d9f2ed}.ma-link,.ma-button{display:inline-flex;justify-content:center;border-radius:.65rem;padding:.7rem 1rem;font-weight:800}.ma-link{border:1px solid #ffffff88}.ma-grid{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.2fr);gap:1.25rem}.ma-card{padding:1.25rem}.ma-card h2{color:#263f57;font-size:1.05rem;font-weight:800}.ma-info{margin-top:.8rem;border-radius:.7rem;background:#f0f8f5;padding:.9rem}.ma-info strong{display:block;color:#197055}.ma-muted{color:#708197;font-size:.82rem}.ma-actions{justify-content:flex-start;flex-wrap:wrap;margin-top:1rem}.ma-button{border:0;background:#1559ba;color:#fff}.ma-button:disabled{opacity:.5}.ma-location{background:#108064}.ma-checkout{background:#d77b13}.ma-file{margin-top:.65rem;width:100%;border:1px dashed #b8c7d7;border-radius:.65rem;padding:.7rem}.ma-table-wrap{overflow:auto}.ma-table{width:100%;min-width:35rem;margin-top:.8rem;border-collapse:collapse}.ma-table th,.ma-table td{padding:.75rem;border-bottom:1px solid #e5ebf1;text-align:left;font-size:.78rem}.ma-table th{font-size:.68rem;text-transform:uppercase}.ma-error{margin-top:.7rem;color:#c93442;font-size:.82rem}.ma-badge{border-radius:999px;background:#e4f4ee;padding:.3rem .6rem;color:#147557;font-size:.72rem;font-weight:800}.dark .ma-card,.dark .ma-file{border-color:#364152;background:#171b22}.dark .ma-card h2{color:#e5edf7}@media(max-width:800px){.ma-grid{grid-template-columns:1fr}.ma-head{align-items:flex-start;flex-direction:column}}
</style>
<section class="ma-hero"><div class="ma-head"><div><h1 class="ma-title">Presensi Saya</h1><p class="ma-sub">{{ $todayLabel }}</p></div><a href="{{ $leaveUrl }}" class="ma-link">Ajukan Izin</a></div></section>
<section class="ma-grid">
<article class="ma-card"><h2>Profil Presensi</h2>@if($employee)<div class="ma-info"><strong>{{ $employee->name }}</strong><span>{{ $employee->school?->name ?? '-' }} &middot; {{ $employee->employee_code }}</span></div>@else<div class="ma-error">Akun belum terhubung dengan data pegawai dan sekolah.</div>@endif @if($setting)<div class="ma-info"><strong>Jadwal hari ini</strong><span>Masuk {{ substr($setting->check_in_start,0,5) }} &middot; terlambat setelah {{ substr($setting->late_after,0,5) }} &middot; pulang {{ substr($setting->check_out_start,0,5) }}</span><p class="ma-muted">{{ $setting->require_location ? 'GPS wajib.' : 'GPS tidak diwajibkan.' }} {{ $setting->require_selfie ? 'Selfie wajib.' : 'Selfie opsional.' }}</p></div>@endif</article>
<article class="ma-card"><div class="ma-status"><h2>Presensi Hari Ini</h2>@if($todayRecord)<span class="ma-badge">{{ $statusOptions[$todayRecord->status] ?? $todayRecord->status }}</span>@endif</div><div class="ma-info"><strong>{{ $todayRecord ? ($statusOptions[$todayRecord->status] ?? $todayRecord->status) : 'Belum presensi' }}</strong><span>Masuk {{ $todayRecord?->check_in_at?->timezone(config('attendance.timezone'))->format('H:i:s') ?? '-' }} &middot; Pulang {{ $todayRecord?->check_out_at?->timezone(config('attendance.timezone'))->format('H:i:s') ?? '-' }}</span></div>
@if($setting?->require_location)<div class="ma-actions"><button type="button" x-on:click="locate" class="ma-button ma-location" x-bind:disabled="locating || submitting" x-text="locating ? 'Mencari lokasi...' : (located ? 'Perbarui Lokasi GPS' : 'Ambil Lokasi GPS')"></button><span class="ma-muted" x-show="located">Lokasi siap digunakan.</span></div>@endif
<label class="ma-muted" style="display:block;margin-top:.9rem">{{ $setting?->require_selfie ? 'Selfie wajib, maksimal 5 MB' : 'Selfie opsional, maksimal 5 MB' }}</label><input type="file" wire:model="selfie" class="ma-file" accept="image/*" capture="user">
<div class="ma-actions">@if(!$todayRecord && $employee && $setting?->is_active && $setting?->enable_check_in)<button type="button" x-on:click="submit('checkIn', @js((bool) $setting?->require_location))" x-bind:disabled="locating || submitting" wire:loading.attr="disabled" class="ma-button" x-text="locating ? 'Mencari GPS...' : (submitting ? 'Mengirim...' : 'Presensi Masuk')">Presensi Masuk</button>@elseif($todayRecord?->check_in_at && !$todayRecord?->check_out_at && $setting?->is_active && $setting?->enable_check_out)<button type="button" x-on:click="submit('checkOut', @js((bool) $setting?->require_location))" x-bind:disabled="locating || submitting" wire:loading.attr="disabled" class="ma-button ma-checkout" x-text="locating ? 'Mencari GPS...' : (submitting ? 'Mengirim...' : 'Presensi Pulang')">Presensi Pulang</button>@elseif($todayRecord?->check_out_at)<span class="ma-muted">Presensi hari ini sudah lengkap.</span>@else<span class="ma-muted">Fitur presensi terkait sedang dinonaktifkan.</span>@endif</div>@error('attendance')<p class="ma-error">{{ $message }}</p>@enderror @foreach (['latitude', 'longitude', 'accuracy'] as $gpsField) @error($gpsField)<p style="color:#dc3948;font-size:12px">{{ $message }}</p>@enderror @endforeach @error('selfie')<p class="ma-error">{{ $message }}</p>@enderror</article>
</section>
<section class="ma-card ma-table-wrap"><h2>Riwayat Presensi Terbaru</h2><table class="ma-table"><thead><tr><th>Tanggal</th><th>Status</th><th>Masuk</th><th>Pulang</th></tr></thead><tbody>@forelse($recentRecords as $record)<tr><td>{{ $record->attendance_date?->format('d-m-Y') }}</td><td>{{ $statusOptions[$record->status] ?? $record->status }}</td><td>{{ $record->check_in_at?->timezone(config('attendance.timezone'))->format('H:i:s') ?? '-' }}</td><td>{{ $record->check_out_at?->timezone(config('attendance.timezone'))->format('H:i:s') ?? '-' }}</td></tr>@empty<tr><td colspan="4">Belum ada riwayat presensi.</td></tr>@endforelse</tbody></table></section>
</div>

@assets
<script src="{{ asset('js/attendance-gps.js').'?v='.filemtime(public_path('js/attendance-gps.js')) }}"></script>
@endassets
