<x-filament-panels::page>
@include('filament.app.mobile.styles')
<style>
.complaint-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(20rem,.8fr);gap:1rem}.complaint-form{display:grid;gap:.8rem}.complaint-label{display:grid;gap:.35rem;font-size:.78rem;font-weight:700;color:#344054}.complaint-input{width:100%;border:1px solid #d0d5dd;border-radius:.75rem;padding:.75rem;background:#fff}.complaint-button{border:0;border-radius:.75rem;background:#047857;color:#fff;font-weight:700;padding:.8rem 1rem;cursor:pointer}.complaint-item{width:100%;text-align:left;border:1px solid #e4e7ec;border-radius:.8rem;background:#fff;padding:.8rem;margin-top:.55rem}.complaint-item strong,.complaint-item span{display:block}.complaint-item small{color:#667085}.complaint-privacy{border-radius:.8rem;background:#ecfdf3;color:#065f46;padding:.8rem;font-size:.8rem}.complaint-response{margin-top:.8rem;border-left:3px solid #10b981;background:#f0fdf4;padding:.75rem}.complaint-empty{color:#667085;font-size:.85rem;padding:.75rem 0}@media(max-width:800px){.complaint-grid{grid-template-columns:1fr}}
</style>
<div class="teacher-mobile">
 @include('filament.app.mobile.header',['employee'=>$employee])
 <section class="tm-hero"><div><div class="tm-eyebrow">Saluran Privat</div><h1>Pengaduan Saya</h1><p>Sampaikan permasalahan sekolah langsung kepada pengurus yayasan.</p></div></section>
 <section class="tm-section complaint-privacy">🔒 Pengaduan hanya dapat dibaca oleh Anda dan admin induk yayasan. Admin sekolah dan pengguna lain tidak memiliki akses.</section>
 <section class="tm-section">
  <article class="tm-card" style="padding:1rem"><h2>Buat Pengaduan</h2><form wire:submit="submitComplaint" class="complaint-form">
   <label class="complaint-label">Kategori<select wire:model="category" class="complaint-input"><option value="">Pilih kategori</option>@foreach($categories as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select>@error('category')<small style="color:#b42318">{{ $message }}</small>@enderror</label>
   <label class="complaint-label">Judul<input wire:model="subject" class="complaint-input" maxlength="255" placeholder="Ringkasan masalah">@error('subject')<small style="color:#b42318">{{ $message }}</small>@enderror</label>
   <label class="complaint-label">Kronologi<textarea wire:model="description" class="complaint-input" rows="6" maxlength="10000" placeholder="Jelaskan kejadian, waktu, lokasi, dan dampaknya"></textarea>@error('description')<small style="color:#b42318">{{ $message }}</small>@enderror</label>
   <label class="complaint-label">Foto/Dokumen Pendukung<input wire:model="attachments" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx" class="complaint-input"><small>Maksimal 5 file, masing-masing 10 MB. Format JPG, PNG, WEBP, PDF, DOC, atau DOCX.</small>@error('attachments')<small style="color:#b42318">{{ $message }}</small>@enderror @error('attachments.*')<small style="color:#b42318">{{ $message }}</small>@enderror</label>
   @if($attachments)<div class="complaint-privacy">{{ count($attachments) }} file siap diunggah.</div>@endif
   <button class="complaint-button" type="submit" wire:loading.attr="disabled">Kirim Pengaduan Privat</button>
  </form></article>
 </section>
 @include('filament.app.mobile.bottom-nav',['active'=>'complaints'])
</div>
<div class="teacher-desktop"><section class="tp-hero"><small>SALURAN PRIVAT</small><h1>Pengaduan Saya</h1><p>Hanya Anda dan admin induk yayasan yang dapat mengakses pengaduan ini.</p></section><section class="complaint-grid" style="margin-top:1rem"><article class="tp-card"><h2>Buat Pengaduan</h2><form wire:submit="submitComplaint" class="complaint-form"><label class="complaint-label">Kategori<select wire:model="category" class="complaint-input"><option value="">Pilih kategori</option>@foreach($categories as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="complaint-label">Judul<input wire:model="subject" class="complaint-input"></label><label class="complaint-label">Kronologi<textarea wire:model="description" class="complaint-input" rows="7"></textarea></label><label class="complaint-label">Foto/Dokumen Pendukung<input wire:model="attachments" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx" class="complaint-input"><small>Maksimal 5 file × 10 MB.</small></label><button class="complaint-button">Kirim Pengaduan Privat</button></form></article><article class="tp-card"><h2>Riwayat</h2>@forelse($complaints as $complaint)<button wire:click="selectComplaint({{ $complaint->id }})" class="complaint-item"><small>{{ $complaint->reference_number }}</small><strong>{{ $complaint->subject }}</strong><span>{{ $statuses[$complaint->status] ?? $complaint->status }}</span></button>@empty<p>Belum ada pengaduan.</p>@endforelse @if($selectedComplaint)@if($selectedComplaint->attachments)<div class="complaint-response"><strong>Lampiran</strong>@foreach($selectedComplaint->attachments as $index=>$file)<p><a href="{{ route('complaints.attachments.view',[$selectedComplaint,$index]) }}" target="_blank">📎 {{ $file['name'] ?? 'Lampiran' }}</a></p>@endforeach</div>@endif<div class="complaint-response"><strong>Tanggapan Yayasan</strong><p>{{ $selectedComplaint->admin_response ?: 'Belum ada tanggapan.' }}</p></div>@endif</article></section></div>
</x-filament-panels::page>
