<x-filament-panels::page>
@include('filament.app.mobile.styles')
<div class="teacher-mobile">
 @include('filament.app.mobile.header',['employee'=>$employee])
 <section class="tm-hero"><img class="tm-hero-avatar" src="{{ $avatarUrl }}"><div><div class="tm-eyebrow">Profile</div><h1>{{ $employee?->name ?? $user?->name }}</h1><p>{{ $employee?->email ?? $user?->email }}</p></div></section>
 <section class="tm-section tm-stats"><article class="tm-card tm-stat"><span>Rekan Sekolah</span><strong>{{ $colleagueCount }}</strong><small>Guru/Pegawai satu lembaga</small></article><article class="tm-card tm-stat"><span>Total Pembayaran</span><strong>Rp{{ number_format($paidAmount,0,',','.') }}</strong><small>Pembayaran lunas</small></article></section>
 <section class="tm-section"><div class="tm-section-head"><h2>Detail Akun</h2><small>{{ $invoiceCount }} pembayaran SK</small></div><div class="tm-card tm-detail">@foreach([['Nama Lengkap',$employee?->name ?? $user?->name],['Asal Madrasah/Sekolah',$employee?->school?->name ?? '-'],['Status Kepegawaian',$employee ? \App\Models\Employee::employmentStatusLabel($employee->employment_status) : '-'],['Ketugasan',$employee?->currentAssignment?->position?->name ?? '-'],['Nomor HP',$employee?->phone ?? $user?->phone_number ?? '-'],['Alamat',$employee?->address ?? '-'],['Periode SK Yayasan',$employee?->currentAssignment?->decree_period ?? '-']] as [$label,$value])<div class="tm-detail-row"><span>{{ $label }}</span><strong>{{ $value }}</strong></div>@endforeach</div></section>
 @include('filament.app.mobile.bottom-nav',['active'=>'profile'])
</div>
<div class="teacher-desktop"><section class="tp-hero"><small>PROFIL GURU/PEGAWAI</small><h1>{{ $employee?->name ?? $user?->name }}</h1><p>{{ $employee?->email ?? $user?->email }}</p></section><div class="tp-grid"><article class="tp-card"><h2>Ringkasan</h2><div class="tp-row"><span>Rekan Sekolah</span><strong>{{ $colleagueCount }}</strong></div><div class="tp-row"><span>Total Pembayaran</span><strong>Rp{{ number_format($paidAmount,0,',','.') }}</strong></div></article><article class="tp-card"><h2>Detail Akun</h2>@foreach([['Nama Lengkap',$employee?->name ?? $user?->name],['Asal Madrasah/Sekolah',$employee?->school?->name ?? '-'],['Status Kepegawaian',$employee ? \App\Models\Employee::employmentStatusLabel($employee->employment_status) : '-'],['Ketugasan',$employee?->currentAssignment?->position?->name ?? '-'],['Nomor HP',$employee?->phone ?? $user?->phone_number ?? '-'],['Alamat',$employee?->address ?? '-'],['Periode SK Yayasan',$employee?->currentAssignment?->decree_period ?? '-']] as [$label,$value])<div class="tp-row"><span>{{ $label }}</span><strong>{{ $value }}</strong></div>@endforeach</article></div></div>
</x-filament-panels::page>
