<x-filament-panels::page>
@include('filament.app.mobile.styles')
<div class="teacher-mobile">
 @include('filament.app.mobile.header',['employee'=>$employee])
 <section class="tm-hero"><div><div class="tm-eyebrow">Pembayaran SK Yayasan</div><h1>Pembayaran Terkait SK</h1></div></section>
 <section class="tm-section tm-stats"><article class="tm-card tm-stat"><span>Total Pembayaran</span><strong>{{ $invoices->count() }}</strong><small>Pembayaran SK Yayasan</small></article><article class="tm-card tm-stat"><span>Nominal</span><strong>Rp{{ number_format($totalAmount,0,',','.') }}</strong><small>Akumulasi nilai pembayaran</small></article><article class="tm-card tm-stat"><span>Lunas</span><strong>{{ $paidCount }}</strong><small>Sudah dibayarkan</small></article><article class="tm-card tm-stat"><span>Pending</span><strong>{{ $pendingCount }}</strong><small>Menunggu penyelesaian</small></article></section>
 <section class="tm-section"><div class="tm-section-head"><h2>Daftar Pembayaran</h2><small>{{ $employee?->school?->name }}</small></div><div class="tm-card tm-list">@forelse($invoices as $invoice)<div class="tm-list-row"><div><strong>{{ $invoice->description }}</strong><span>{{ $invoice->academic_year }} &bull; Rp{{ number_format($invoice->amount,0,',','.') }}</span><small>{{ $invoice->paymentMethodLabel() }}</small></div><span class="tm-badge {{ $invoice->status===\App\Models\PaymentInvoice::STATUS_PAID?'tm-success':'tm-danger' }}">{{ $invoice->status===\App\Models\PaymentInvoice::STATUS_PAID?'Lunas':'Pending' }}</span></div>@empty<div class="tm-empty">Belum ada pembayaran untuk akun ini.</div>@endforelse</div></section>
 @include('filament.app.mobile.bottom-nav',['active'=>'payments'])
</div>
<div class="teacher-desktop"><section class="tp-hero"><small>PEMBAYARAN SK YAYASAN</small><h1>Pembayaran Terkait SK</h1></section><div class="tp-grid"><article class="tp-card"><h2>Ringkasan Pembayaran</h2><div class="tp-row"><span>Total Pembayaran</span><strong>{{ $invoices->count() }}</strong></div><div class="tp-row"><span>Nominal</span><strong>Rp{{ number_format($totalAmount,0,',','.') }}</strong></div><div class="tp-row"><span>Lunas</span><strong>{{ $paidCount }}</strong></div><div class="tp-row"><span>Pending</span><strong>{{ $pendingCount }}</strong></div></article><article class="tp-card"><h2>Daftar Pembayaran</h2>@forelse($invoices as $invoice)<div class="tp-row"><span>{{ $invoice->description }}<br><small>{{ $invoice->academic_year }}</small></span><strong>Rp{{ number_format($invoice->amount,0,',','.') }}<br><small>{{ $invoice->status===\App\Models\PaymentInvoice::STATUS_PAID?'Lunas':'Pending' }}</small></strong></div>@empty<div class="tp-empty">Belum ada pembayaran untuk akun ini.</div>@endforelse</article></div></div>
</x-filament-panels::page>
