<div class="al-page">
<style>
.al-page{--blue:#164db9;display:grid;gap:1.25rem;padding-top:.5rem;color:#475569}.al-page *{box-sizing:border-box}.al-header,.al-card,.al-stat{border:1px solid #e2e8f0;border-radius:12px;background:#fff;box-shadow:0 2px 8px rgba(15,23,42,.05)}
.al-header{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;padding:20px 24px}.al-title{margin:0;color:#1e293b;font-size:clamp(28px,3vw,32px);font-weight:700;line-height:1.2;letter-spacing:-.025em}.al-sub{margin:.35rem 0 0;color:#94a3b8;font-size:14px}.al-head-actions{display:grid;justify-items:end;gap:.7rem}.al-crumb{color:#94a3b8;font-size:12px;white-space:nowrap}.al-crumb strong{color:#64748b}.al-link{display:inline-flex;align-items:center;gap:.45rem;height:40px;padding:0 14px;border:1px solid var(--blue);border-radius:8px;background:#fff;color:var(--blue);font-size:13px;font-weight:700;text-decoration:none}.al-link:hover{background:#eff6ff}.al-icon{width:19px;height:19px;flex:none}
.al-filter-card{padding:22px 24px}.al-filter{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(13rem,1fr);gap:16px 20px;align-items:end}.al-field{display:grid;gap:7px;min-width:0}.al-label{color:#64748b;font-size:12px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.al-input,.al-note{width:100%;border:1px solid #cbd5e1;border-radius:8px;background:#fff;color:#334155;outline:none;transition:.15s}.al-input{height:48px;padding:0 16px;font-size:15px}.al-input:focus,.al-note:focus{border-color:var(--blue);box-shadow:0 0 0 3px rgba(22,77,185,.12)}.al-input::placeholder{color:#94a3b8}
.al-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.al-stat{min-height:116px;display:flex;align-items:center;gap:16px;padding:20px}.al-stat-icon{display:grid;place-items:center;width:56px;height:56px;flex:0 0 56px;border-radius:50%}.al-stat-copy{display:grid;gap:3px}.al-stat-label{color:#64748b;font-size:14px;font-weight:600}.al-stat-value{color:#334155;font-size:30px;font-weight:700;line-height:1}.al-stat-pending{border-color:#fed7aa}.al-stat-pending .al-stat-icon{background:#fff4db;color:#d97706}.al-stat-approved .al-stat-icon{background:#dcfce7;color:#16a34a}.al-stat-rejected .al-stat-icon{background:#fee2e2;color:#dc2626}.al-stat-total .al-stat-icon{background:#e0e7ff;color:#4f46e5}
.al-table-card{overflow:hidden}.al-table-head{padding:20px 24px 16px}.al-table-head h2{margin:0;color:#334155;font-size:16px;font-weight:700}.al-table-head p{margin:4px 0 0;color:#94a3b8;font-size:13px}.al-table-wrap{margin:0 24px 24px;overflow-x:auto;border:1px solid #e2e8f0;border-radius:10px}.al-table{width:100%;min-width:72rem;border-collapse:collapse}.al-table th,.al-table td{padding:13px 14px;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:middle;font-size:12.5px;line-height:1.45}.al-table th{background:#f8fafc;color:#64748b;font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}.al-table tbody tr{min-height:56px}.al-table tbody tr:not(.al-empty-row):hover{background:#f8fafc}.al-table tbody tr:last-child td{border-bottom:0}.al-reason{min-width:12rem;max-width:20rem}.al-note{min-width:12rem;height:38px;padding:0 11px;font-size:12.5px}.al-actions{white-space:nowrap}.al-button{min-height:34px;border:0;border-radius:7px;padding:0 11px;color:#fff;cursor:pointer;font-size:11.5px;font-weight:700}.al-button:hover{filter:brightness(.93)}.al-button+.al-button{margin-left:5px}.al-approve{background:#169854}.al-reject{background:#dc2626}.al-badge{display:inline-flex;border-radius:999px;padding:5px 10px;font-size:11px;font-weight:700;white-space:nowrap}.al-badge-pending{background:#fff4db;color:#b45309}.al-badge-approved{background:#dcfce7;color:#15803d}.al-badge-rejected{background:#fee2e2;color:#b91c1c}.al-badge-default{background:#f1f5f9;color:#475569}
.al-empty{height:210px;text-align:center!important}.al-empty-content{display:flex;min-height:180px;flex-direction:column;align-items:center;justify-content:center;gap:7px;color:#94a3b8}.al-empty-icon{display:grid;place-items:center;width:56px;height:56px;margin-bottom:4px;border-radius:50%;background:#eff6ff;color:#3b82f6}.al-empty-icon svg{width:27px;height:27px}.al-empty strong{color:#475569;font-size:14px}.al-empty span{font-size:12.5px}
.dark .al-header,.dark .al-card,.dark .al-stat,.dark .al-input,.dark .al-note,.dark .al-link{border-color:#364152;background:#171b22}.dark .al-title,.dark .al-stat-value,.dark .al-table-head h2,.dark .al-input,.dark .al-note{color:#e5edf7}.dark .al-table th{background:#202630;color:#aab7c7}.dark .al-table th,.dark .al-table td,.dark .al-table-wrap{border-color:#364152}.dark .al-table tbody tr:not(.al-empty-row):hover{background:#202630}
@media(max-width:900px){.al-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.al-page{padding-top:.75rem}.al-header{flex-direction:column;padding:18px 20px}.al-head-actions{width:100%;justify-items:start}.al-filter-card{padding:18px 20px}.al-filter{grid-template-columns:1fr}.al-table-head{padding:18px 20px 14px}.al-table-wrap{margin:0 20px 20px}}@media(max-width:440px){.al-stats{grid-template-columns:1fr}.al-stat{min-height:108px}}
</style>
@php
$pendingCount=$requests->where('status','pending')->count();
$approvedCount=$requests->where('status','approved')->count();
$rejectedCount=$requests->where('status','rejected')->count();
@endphp
<header class="al-header"><div><h1 class="al-title">Pengajuan Izin</h1><p class="al-sub">Dashboard pusat pengajuan izin seluruh sekolah.</p></div><div class="al-head-actions"><div class="al-crumb" aria-label="Breadcrumb">Home / Dashboard / <strong>Pengajuan Izin</strong></div><a href="{{ $dashboardUrl }}" class="al-link"><svg class="al-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M3 13.5h6v7H3v-7Zm12-10h6v17h-6v-17Zm-6 5h6v12H9v-12Z"/></svg>Dashboard</a></div></header>
<section class="al-card al-filter-card" aria-label="Filter pengajuan izin"><div class="al-filter"><label class="al-field"><span class="al-label">Cari Pengajuan</span><input type="search" wire:model.live.debounce.300ms="search" class="al-input" placeholder="Cari nama, sekolah, atau alasan..."></label><label class="al-field"><span class="al-label">Status</span><select wire:model.live="selectedStatus" class="al-input"><option value="">Semua status</option>@foreach($statusOptions as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label></div></section>
<section class="al-stats" aria-label="Ringkasan pengajuan izin">
@foreach([['pending','Menunggu',$pendingCount,'M12 6v6l4 2m5-2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z'],['approved','Disetujui',$approvedCount,'m9 12 2 2 4-4m6 2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z'],['rejected','Ditolak',$rejectedCount,'m9 9 6 6m0-6-6 6m12-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z'],['total','Total',$requests->count(),'M3 13.5h6v7H3v-7Zm12-10h6v17h-6v-17Zm-6 5h6v12H9v-12Z']] as [$class,$label,$value,$path])<article class="al-stat al-stat-{{ $class }}"><span class="al-stat-icon"><svg class="al-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="{{ $path }}"/></svg></span><span class="al-stat-copy"><span class="al-stat-label">{{ $label }}</span><strong class="al-stat-value">{{ number_format($value) }}</strong></span></article>@endforeach
</section>
<section class="al-card al-table-card"><div class="al-table-head"><h2>Daftar Pengajuan</h2><p>Periksa detail dan tindak lanjuti pengajuan yang masih menunggu.</p></div><div class="al-table-wrap"><table class="al-table"><thead><tr><th>Nama</th><th>Sekolah</th><th>Jenis</th><th>Periode</th><th>Alasan</th><th>Status</th><th>Catatan Admin</th><th>Aksi</th></tr></thead><tbody>
@forelse($requests as $request)
@php $badgeClass=match($request->status){'pending'=>'pending','approved'=>'approved','rejected'=>'rejected',default=>'default'}; @endphp
<tr><td><strong>{{ $request->employee?->name??'-' }}</strong></td><td>{{ $request->school?->name??'-' }}</td><td>{{ $typeOptions[$request->leave_type]??$request->leave_type }}</td><td>{{ $request->start_date?->format('d-m-Y') }} s/d {{ $request->end_date?->format('d-m-Y') }}</td><td class="al-reason">{{ $request->reason }}</td><td><span class="al-badge al-badge-{{ $badgeClass }}">{{ $statusOptions[$request->status]??$request->status }}</span></td><td>@if($request->status==='pending')<input type="text" wire:model="reviewNotes.{{ $request->getKey() }}" class="al-note" placeholder="Catatan opsional">@else{{ $request->review_notes?:'-' }}@endif</td><td class="al-actions">@if($request->status==='pending')<button type="button" wire:click="approve({{ $request->getKey() }})" class="al-button al-approve">Setujui</button><button type="button" wire:click="reject({{ $request->getKey() }})" class="al-button al-reject">Tolak</button>@else-@endif</td></tr>
@empty
<tr class="al-empty-row"><td colspan="8" class="al-empty"><div class="al-empty-content"><span class="al-empty-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M3 13.5V6.75A2.25 2.25 0 0 1 5.25 4.5h13.5A2.25 2.25 0 0 1 21 6.75v6.75m-18 0 2.2 4.4a2.25 2.25 0 0 0 2.01 1.24h9.58a2.25 2.25 0 0 0 2.01-1.24l2.2-4.4h-5.25l-1.5 2.25h-4.5l-1.5-2.25H3Z"/></svg></span><strong>Belum ada pengajuan izin.</strong><span>Data pengajuan izin akan muncul di sini.</span></div></td></tr>
@endforelse
</tbody></table></div></section>
</div>
