<?php
namespace Tests\Feature\FoundationSk;
use App\Contracts\{FoundationSkDocumentWriter,FoundationSkPdfWriter}; use App\Models\{FoundationSkDocument,FoundationSkNumberSetting,FoundationSkTemplate,User}; use App\Services\FoundationSkBatchGenerationService; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Storage; use Mockery; use Tests\TestCase;
class FoundationSkBatchFailureTest extends TestCase {
 use RefreshDatabase;
 private function actor(){ $a=Mockery::mock(User::class);$a->shouldReceive('isAdminInduk')->andReturn(true);$a->shouldReceive('can')->andReturn(true);return $a; }
 private function data(){ $t=FoundationSkTemplate::create(['name'=>'T','slug'=>'t-'.uniqid(),'paper_size'=>'A4','orientation'=>'portrait','html_template'=>'{{nomor_sk}}','content'=>'{{nomor_sk}}','is_active'=>true]);FoundationSkNumberSetting::create(['periode'=>'2026/2027','nomor_pattern'=>'SK/{{nomor_urut}}','nomor_awal'=>1,'nomor_berikutnya'=>1,'digit_nomor'=>3,'is_active'=>true]);return [$t,User::factory()->count(2)->create()]; }
 private function runBatch($t,$users,$pdf,$docs){$this->app->instance(FoundationSkPdfWriter::class,$pdf);$this->app->instance(FoundationSkDocumentWriter::class,$docs);try{app(FoundationSkBatchGenerationService::class)->generate($t,$users->all(),'2026/2027',$this->actor());}catch(\Throwable $e){return $e;}return null;}
 public function test_pdf_failure_on_second_user_rolls_back():void {Storage::fake('documents');[$t,$users]=$this->data();$pdf=Mockery::mock(FoundationSkPdfWriter::class);$pdf->shouldReceive('generateSingle')->once()->andReturn('%PDF-1.4 one');$pdf->shouldReceive('generateSingle')->once()->andThrow(new \RuntimeException('pdf failed'));$docs=Mockery::mock(FoundationSkDocumentWriter::class);$docs->shouldReceive('storeFile')->once()->andReturn(true);$docs->shouldReceive('createOrUpdate')->once()->andReturn(FoundationSkDocument::make());$docs->shouldReceive('cleanupFiles')->once()->withArgs(fn($p)=>count($p)===1);$this->assertInstanceOf(\RuntimeException::class,$this->runBatch($t,$users,$pdf,$docs));$this->assertSame(1,FoundationSkNumberSetting::first()->nomor_berikutnya);$this->assertDatabaseCount('foundation_sk_documents',0);}
 public function test_document_writer_failure_rolls_back():void {Storage::fake('documents');[$t,$users]=$this->data();$pdf=Mockery::mock(FoundationSkPdfWriter::class);$pdf->shouldReceive('generateSingle')->twice()->andReturn('%PDF-1.4');$docs=Mockery::mock(FoundationSkDocumentWriter::class);$docs->shouldReceive('storeFile')->twice()->andReturn(true);$docs->shouldReceive('createOrUpdate')->once()->andReturn(FoundationSkDocument::make())->ordered();$docs->shouldReceive('createOrUpdate')->once()->andThrow(new \RuntimeException('writer failed'))->ordered();$docs->shouldReceive('cleanupFiles')->once()->withArgs(fn($p)=>count($p)===2);$this->assertInstanceOf(\RuntimeException::class,$this->runBatch($t,$users,$pdf,$docs));$this->assertSame(1,FoundationSkNumberSetting::first()->nomor_berikutnya);$this->assertDatabaseCount('foundation_sk_documents',0);}
}
