@php
    $value = static function (string $key, mixed $fallback = null) use ($get, $record): mixed {
        if (isset($get) && is_callable($get)) return $get($key) ?? $fallback;
        return data_get($record, $key, $fallback);
    };
    $builder = $value('builder_data', $record?->builder_data ?? \App\Models\FoundationSkTemplate::defaultBuilderData()) ?: [];
    $header = $builder['header'] ?? []; $decision = $builder['decision'] ?? []; $sections = $builder['sections'] ?? [];
    $content = $value('content', $record?->content ?? ''); $customCss = $value('custom_css', $record?->custom_css ?? '');
    $size = $value('paper_size', $record?->paper_size ?? 'A4'); $orientation = $value('orientation', $record?->orientation ?? 'portrait');
    $dimensions = match ($size) { 'F4' => [816, 1248], 'Legal', 'LEGAL' => [816, 1344], 'LETTER' => [816, 1056], default => [794, 1123] };
    if ($orientation === 'landscape') $dimensions = [$dimensions[1], $dimensions[0]];
@endphp
<div x-data="{ zoom: 100, min: 50, max: 200, step: 10, zoomIn() { this.zoom = Math.min(this.max, this.zoom + this.step) }, zoomOut() { this.zoom = Math.max(this.min, this.zoom - this.step) }, reset() { this.zoom = 100 } }" class="foundation-sk-preview flex min-h-[700px] min-w-0 flex-col rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-900">
    <div class="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-base font-semibold text-gray-950 dark:text-white">Preview Hasil PDF</h2><p class="text-sm text-gray-500">Preview otomatis menggunakan data contoh.</p><p class="mt-1 text-xs text-gray-400">Gunakan zoom untuk melihat detail layout.</p></div><div class="flex items-center gap-1" role="toolbar"><button type="button" class="preview-zoom-button" x-on:click="zoomOut()" x-bind:disabled="zoom <= min" aria-label="Perkecil preview">−</button><span class="min-w-[52px] text-center text-sm font-medium" x-text="`${zoom}%`">100%</span><button type="button" class="preview-zoom-button" x-on:click="zoomIn()" x-bind:disabled="zoom >= max" aria-label="Perbesar preview">+</button><button type="button" class="preview-reset-button" x-on:click="reset()">Reset</button></div></div>
    <div class="preview-scroll-area min-h-0 flex-1 overflow-auto rounded-lg border border-gray-200 bg-gray-100 p-6 dark:border-gray-700 dark:bg-gray-800">
        <div class="mx-auto" style="width: {{ $dimensions[0] }}px; height: {{ $dimensions[1] }}px" x-bind:style="`width: {{ $dimensions[0] }}px; height: {{ $dimensions[1] }}px`"><div class="preview-document origin-top shadow-lg" style="width: {{ $dimensions[0] }}px; min-height: {{ $dimensions[1] }}px; transform: scale(1); transform-origin: top center" x-bind:style="`width: {{ $dimensions[0] }}px; min-height: {{ $dimensions[1] }}px; transform: scale(${zoom / 100}); transform-origin: top center`">
            @if (!empty($header['logo_path']))<div class="text-center" style="padding-top:18px"><img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($header['logo_path']) }}" alt="Logo kop surat" style="max-height:76px;max-width:180px;object-fit:contain"></div>@else<div style="height:18px"></div>@endif
            @if ($customCss)<style>{!! $customCss !!}</style>@endif
            <style>.preview-document>div[style*="padding:42px"]>div:nth-child(-n+6){color:#15803d!important}.preview-document hr{border:0;border-top:3px solid #15803d;margin:14px 0}.preview-letterhead img{max-height:76px;max-width:180px;object-fit:contain}</style>
            <div style="padding:42px;font-family:serif;font-size:{{ $builder['fonts']['body'] ?? 11 }}px;background:white;min-height:{{ $dimensions[1] }}px;color:#111827"><div style="text-align:center;font-size:{{ $header['font_top_text'] ?? 13 }}px">{{ $header['top_text'] ?: 'KEPALA SURAT YAYASAN' }}</div>@if (!empty($header['logo_path']))<div style="text-align:center;margin:8px">Logo kop surat</div>@endif<div style="text-align:center;font-weight:700;font-size:{{ $header['font_institution_name'] ?? 26 }}px">{{ $header['institution_name'] ?: 'YAYASAN CONTOH' }}</div><div style="text-align:center">{{ $header['address'] ?: 'Alamat lembaga' }}</div>@if ($header['whatsapp'] || $header['email'])<div style="text-align:center;font-size:{{ $header['font_contact'] ?? 11 }}px">{{ $header['whatsapp'] }} @if ($header['whatsapp'] && $header['email']) · @endif {{ $header['email'] }}</div>@endif<hr><div style="text-align:center;font-weight:700;font-size:{{ $decision['font_title'] ?? 13 }}px">{{ $decision['title'] ?: 'SURAT KEPUTUSAN' }}</div><div style="text-align:center">{{ $decision['number'] ?: 'Nomor: 0001/SK/YYS/2026' }}</div>@if (filled($content))<div>{!! $content !!}</div>@else<p>{{ $decision['opening'] ?: 'Dengan ini menetapkan keputusan sebagai berikut:' }}</p>@foreach (['menimbang'=>'Menimbang','mengingat'=>'Mengingat','memutuskan'=>'Memutuskan','menetapkan'=>'Menetapkan'] as $key=>$label)@if (!empty($sections[$key]))<p><strong>{{ $label }}:</strong> {{ $sections[$key] }}</p>@endif @endforeach @endif<p>Nama: <strong>Nama Lengkap Contoh</strong><br>NIS/NIP/NUPTK: 0000000000<br>Sekolah: Sekolah Contoh</p></div>
        </div></div>
    </div>
</div>
<style>.preview-zoom-button,.preview-reset-button{height:32px;border:1px solid #cbd5e1;border-radius:6px;background:#fff;padding:0 10px;font-size:13px;color:#475569}.preview-zoom-button{width:32px;padding:0;font-size:20px}.preview-zoom-button:hover,.preview-reset-button:hover{background:#f1f5f9}.preview-zoom-button:disabled{cursor:not-allowed;opacity:.45}.preview-zoom-button:focus-visible,.preview-reset-button:focus-visible{outline:2px solid #10b981;outline-offset:2px}@media(max-width:767px){.foundation-sk-preview{min-height:560px;padding:1rem}.preview-scroll-area{padding:1rem}}</style>
