<?php
namespace App\Filament\Admin\Pages;
use App\Models\{FoundationSkDocument,FoundationSkTemplate,School,User};
use App\Services\{FoundationSkDocumentService,FoundationSkMatchingService};
use Filament\Pages\Page; use Filament\Schemas\Components\View; use Filament\Schemas\Schema; use Illuminate\Support\Facades\DB; use Livewire\WithFileUploads;
class FoundationSkDashboard extends Page
{
 use WithFileUploads;
 protected static ?string $slug='foundation-sk-dashboard'; protected static ?string $title='Dashboard SK Yayasan'; protected static bool $shouldRegisterNavigation=false;
 public int $tahunSk; public ?int $skTemplateId=null; public ?int $uploadUserId=null; public ?int $schoolId=null; public array $files=[]; public $uploadFile=null; public array $result=[];
 public static function canAccess():bool{return auth()->user()?->isAdminInduk()||(auth()->user()?->hasRole(User::ROLE_ADMIN_SEKOLAH_MADRASAH)&&auth()->user()->can('sk-yayasan.view'));}
 public function mount():void{$this->tahunSk=(int)now()->year;}
 private function documentQuery(){ $q=FoundationSkDocument::query();$u=auth()->user();return $u?->isAdminInduk()?$q:$q->whereHas('user.employee',fn($e)=>$e->whereIn('school_id',$u?->accessibleSchoolIds()??[])); }
 public function content(Schema $schema):Schema{return $schema->components([View::make('filament.admin.pages.foundation-sk-dashboard')->viewData(function(){ $q=$this->documentQuery();return ['templates'=>FoundationSkTemplate::where('is_active',true)->orderBy('name')->get(),'users'=>User::query()->whereHas('employee',fn($e)=>$e->where('is_active',true)->whereIn('school_id',auth()->user()?->accessibleSchoolIds()??[]))->orderBy('name')->pluck('name','id'),'schools'=>School::query()->accessibleTo(auth()->user())->where('is_active',true)->pluck('name','id'),'totalTemplates'=>FoundationSkTemplate::count(),'totalDocuments'=>(clone $q)->count(),'currentYearDocuments'=>(clone $q)->where('tahun_sk',now()->year)->count(),'connectedUsers'=>(clone $q)->distinct('user_id')->count('user_id'),'documents'=>(clone $q)->with(['user.employee.school','template'])->latest()->limit(10)->get()];})]);}
 public function uploadSingle():void{abort_unless(auth()->user()?->isAdminInduk()||auth()->user()?->can('sk-yayasan.manage'),403);$this->validate(['uploadUserId'=>'required|integer|exists:users,id','tahunSk'=>'required|integer|min:2000|max:2200','skTemplateId'=>'required|exists:foundation_sk_templates,id','uploadFile'=>'required|file|mimes:pdf,jpg,jpeg,png|max:10240']);$user=User::with('employee')->findOrFail($this->uploadUserId);abort_unless(auth()->user()->isAdminInduk()||auth()->user()->accessibleSchoolIds()->contains($user->employee?->school_id),403);app(FoundationSkDocumentService::class)->store($user,$this->tahunSk,$this->skTemplateId,$this->uploadFile,auth()->user(),'single');$this->reset('uploadFile','uploadUserId');session()->flash('success','Dokumen SK berhasil dihubungkan.');}
 public function importBatch():void{$this->authorizeImport();$this->validate(['tahunSk'=>'required|integer|min:2000|max:2200','skTemplateId'=>'required|exists:foundation_sk_templates,id','schoolId'=>'nullable|integer','files'=>'required|array|min:1','files.*'=>'file|mimes:pdf,jpg,jpeg,png|max:10240']);$this->result=['total_files'=>count($this->files),'matched_count'=>0,'updated_count'=>0,'unmatched_files'=>[],'ambiguous_files'=>[],'error_files'=>[]];$matcher=app(FoundationSkMatchingService::class);foreach($this->files as $file){$match=$matcher->match($file,auth()->user(),$this->schoolId);if($match['status']==='unmatched'){$this->result['unmatched_files'][]=$file->getClientOriginalName();continue;}if($match['status']==='ambiguous'){$this->result['ambiguous_files'][]=$file->getClientOriginalName();continue;}try{$before=$this->documentQuery()->where(['user_id'=>$match['employee']->user_id,'tahun_sk'=>$this->tahunSk,'sk_template_id'=>$this->skTemplateId])->exists();DB::transaction(fn()=>app(FoundationSkDocumentService::class)->store($match['employee']->user,$this->tahunSk,$this->skTemplateId,$file,auth()->user(),'batch',$match['matched_by']));$before?$this->result['updated_count']++:$this->result['matched_count']++;}catch(\Throwable $e){$this->result['error_files'][]=$file->getClientOriginalName();throw $e;}}$this->reset('files');}
 private function authorizeImport():void{abort_unless(static::canAccess()&&auth()->user()->can('sk-yayasan.manage'),403);if($this->schoolId!==null)abort_unless(auth()->user()->isAdminInduk()||auth()->user()->accessibleSchoolIds()->contains($this->schoolId),403);}
}
