<div class="teacher-mobile" x-data="attendanceGps({ maxAccuracy: {{ $setting?->maximum_accuracy_meters ?? 100 }} })">
<p role="status" aria-live="polite" x-show="gpsMessage" x-text="gpsMessage" style="padding:12px;font-size:13px;color:#52657a"></p>
<button type="button" x-cloak x-show="locating" x-on:click="cancel()" style="margin:0 12px 12px;color:#175cd3;font-weight:600">Batalkan pencarian GPS</button>
    @include('filament.app.mobile.header', ['employee'=>$employee])
    <section class="tm-hero"><img class="tm-hero-avatar" src="{{ filled($employee?->avatar_path) ? \Illuminate\Support\Facades\Storage::disk('public')->url($employee->avatar_path) : asset('images/default-avatar.svg') }}"><div><div class="tm-eyebrow">Presensi Kehadiran</div><h1>{{ $employee?->name ?? auth()->user()->name }}</h1><p>{{ $todayLabel }}</p></div></section>
    <div class="tm-clock"><x-filament::icon icon="heroicon-s-clock" style="width:16px"/><span x-data="{time:''}" x-init="setInterval(()=>time=new Date().toLocaleTimeString('id-ID'),1000)" x-text="time"></span></div>
    <section class="tm-section tm-attendance-times"><article class="tm-card tm-time"><span>Jam Masuk</span><strong>{{ $setting ? substr($setting->check_in_start,0,5) : '--:--' }}</strong></article><article class="tm-card tm-time"><span>Jam Pulang</span><strong>{{ $setting ? substr($setting->check_out_start,0,5) : '--:--' }}</strong></article></section>
    <section class="tm-section"><div class="tm-section-head"><h2>Presensi Hari Ini</h2><small>{{ $setting?->require_location ? 'GPS wajib' : 'Tanpa GPS' }}</small></div><article class="tm-card tm-list"><div class="tm-list-row"><div><span>Datang</span><strong>{{ $todayRecord?->check_in_at?->timezone(config('attendance.timezone'))->format('H:i:s') ?? 'Belum presensi' }}</strong></div>@if($todayRecord?->check_in_at)<span class="tm-badge tm-success">Tercatat</span>@elseif($employee && $setting?->is_active && $setting?->enable_check_in)<button type="button" x-on:click="submit('checkIn', @js((bool) $setting?->require_location))" class="tm-primary-button" x-bind:disabled="locating || submitting" wire:loading.attr="disabled" x-text="locating ? 'Mencari GPS...' : (submitting ? 'Mengirim...' : 'Masuk')">Masuk</button>@else<span class="tm-badge">Dinonaktifkan</span>@endif</div><div class="tm-list-row"><div><span>Pulang</span><strong>{{ $todayRecord?->check_out_at?->timezone(config('attendance.timezone'))->format('H:i:s') ?? 'Belum presensi' }}</strong></div>@if($todayRecord?->check_out_at)<span class="tm-badge tm-success">Tercatat</span>@elseif($todayRecord?->check_in_at && $setting?->is_active && $setting?->enable_check_out)<button type="button" x-on:click="submit('checkOut', @js((bool) $setting?->require_location))" class="tm-primary-button" x-bind:disabled="locating || submitting" wire:loading.attr="disabled" x-text="locating ? 'Mencari GPS...' : (submitting ? 'Mengirim...' : 'Pulang')">Pulang</button>@elseif(!$setting?->enable_check_out)<span class="tm-badge">Dinonaktifkan</span>@else<span class="tm-badge">Presensi masuk dahulu</span>@endif</div>@if($setting?->require_selfie)<label style="display:block;padding-top:10px;font-size:12px;font-weight:700">Selfie wajib (maks. 5 MB)</label>@endif<input type="file" wire:model="selfie" accept="image/*" capture="user" style="width:100%;padding:10px 0;font-size:11px">@error('attendance')<p style="color:#dc3948;font-size:12px">{{ $message }}</p>@enderror @foreach (['latitude', 'longitude', 'accuracy'] as $gpsField) @error($gpsField)<p style="color:#dc3948;font-size:12px">{{ $message }}</p>@enderror @endforeach @error('selfie')<p style="color:#dc3948;font-size:12px">{{ $message }}</p>@enderror</article></section>
    <section class="tm-section"><div class="tm-section-head"><h2>Riwayat Terbaru</h2><small>10 aktivitas</small></div><div class="tm-card tm-list">@forelse($recentRecords as $record)<div class="tm-list-row"><div><strong>Presensi - {{ $statusOptions[$record->status] ?? $record->status }}</strong><span>Datang: {{ $record->check_in_at?->timezone('Asia/Jakarta')->format('H:i') ?? '-' }} &bull; Pulang: {{ $record->check_out_at?->timezone('Asia/Jakarta')->format('H:i') ?? '-' }}</span><small>{{ $record->attendance_date?->locale('id')->translatedFormat('d M Y') }}</small></div><span class="tm-badge tm-success">{{ $statusOptions[$record->status] ?? $record->status }}</span></div>@empty<div class="tm-empty">Belum ada riwayat presensi.</div>@endforelse</div></section>
    @include('filament.app.mobile.bottom-nav',['active'=>'attendance'])
</div>

@assets
<script src="{{ asset('js/attendance-gps.js').'?v='.filemtime(public_path('js/attendance-gps.js')) }}"></script>
@endassets
